-- Supabase SQL Editor'da bir kez çalıştır. Mevcut istekleri silmez.
-- Herkes yalnızca istek gönderebilir; anonim ziyaretçiler listeyi okuyamaz.
create table if not exists public.patch_requests (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) on delete set null,
  game_name text not null check (char_length(game_name) between 2 and 100),
  platform text not null check (platform in ('PC','Android','Emülatör','Diğer')),
  details text not null default '' check (char_length(details) <= 500),
  created_at timestamptz not null default now()
);
alter table public.patch_requests alter column user_id drop not null;
alter table public.patch_requests add column if not exists contact_name text;
alter table public.patch_requests add column if not exists contact_email text;
alter table public.patch_requests enable row level security;

drop policy if exists "patch requests own insert" on public.patch_requests;
drop policy if exists "patch requests own and admin read" on public.patch_requests;
drop policy if exists "patch requests public insert" on public.patch_requests;
create policy "patch requests public insert" on public.patch_requests
for insert to anon, authenticated with check (
  (user_id is null or user_id = auth.uid())
  and char_length(btrim(contact_name)) between 2 and 60
  and char_length(btrim(contact_email)) between 3 and 254
  and contact_email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
);
create policy "patch requests own and admin read" on public.patch_requests
for select to authenticated using (user_id = auth.uid() or public.is_admin());

revoke all on public.patch_requests from anon;
grant insert (user_id, contact_name, contact_email, game_name, platform, details)
on public.patch_requests to anon, authenticated;
grant select on public.patch_requests to authenticated;
grant usage, select on sequence public.patch_requests_id_seq to anon, authenticated;
