-- Supabase > SQL Editor'da bir kez çalıştırın.
create table if not exists public.patch_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  game_name text not null check (char_length(game_name) between 2 and 100),
  platform text not null check (platform in ('PC','Android','Emülatör','Diğer')),
  details text not null default '' check (char_length(details) <= 500),
  created_at timestamptz not null default now()
);
create index if not exists patch_requests_user_created_idx on public.patch_requests(user_id,created_at desc);
alter table public.patch_requests enable row level security;
drop policy if exists "patch requests own insert" on public.patch_requests;
drop policy if exists "patch requests own and admin read" on public.patch_requests;
create policy "patch requests own insert" on public.patch_requests for insert to authenticated with check (auth.uid()=user_id);
create policy "patch requests own and admin read" on public.patch_requests for select to authenticated using (auth.uid()=user_id or public.is_admin());
grant select,insert on public.patch_requests to authenticated;
grant usage,select on sequence public.patch_requests_id_seq to authenticated;
