-- TÜRKÇE YAMALAR - Supabase veritabanı kurulumu
-- Supabase > SQL Editor > New query bölümüne bu dosyanın tamamını yapıştırıp RUN deyin.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default 'Kullanıcı' check (char_length(display_name) between 2 and 24),
  avatar_url text,
  role text not null default 'user' check (role in ('user','admin')),
  banned boolean not null default false,
  muted_until timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.comments (
  id bigint generated by default as identity primary key,
  page text not null check (char_length(page) between 1 and 80),
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 800),
  created_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index if not exists comments_page_created_idx on public.comments(page, created_at desc);

create table if not exists public.poll_votes (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  choice text not null check (choice in ('Little Nightmares','Amenti','Throne and Liberty','Assassin’s Creed Valhalla','Diğer')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.presence (
  session_id uuid primary key,
  user_id uuid references public.profiles(id) on delete set null,
  last_seen timestamptz not null default now()
);
create index if not exists presence_last_seen_idx on public.presence(last_seen desc);

-- Yama indirme sayacı: kişisel bilgi tutmaz, sadece toplam sayıyı saklar.
create table if not exists public.download_stats (
  patch_key text primary key check (patch_key ~ '^[a-z0-9-]{1,80}$'),
  download_count bigint not null default 0 check (download_count >= 0),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.profiles(id, display_name)
  values(new.id, coalesce(nullif(new.raw_user_meta_data->>'display_name',''), split_part(new.email,'@',1), 'Kullanıcı'))
  on conflict (id) do nothing;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

-- Eski kullanıcılar varsa profil oluştur
insert into public.profiles(id, display_name, created_at)
select id, coalesce(nullif(raw_user_meta_data->>'display_name',''), split_part(email,'@',1), 'Kullanıcı'), created_at
from auth.users
on conflict (id) do nothing;

alter table public.profiles enable row level security;
alter table public.comments enable row level security;
alter table public.poll_votes enable row level security;
alter table public.presence enable row level security;
alter table public.download_stats enable row level security;

drop policy if exists "download stats public read" on public.download_stats;
create policy "download stats public read" on public.download_stats for select using (true);

create or replace function public.register_download(p_patch_key text)
returns bigint language plpgsql security definer set search_path=public as $$
declare new_count bigint;
begin
  if p_patch_key is null or p_patch_key !~ '^[a-z0-9-]{1,80}$' then
    raise exception 'invalid patch key';
  end if;
  insert into public.download_stats(patch_key,download_count,updated_at)
  values(p_patch_key,1,now())
  on conflict(patch_key) do update
    set download_count=public.download_stats.download_count+1, updated_at=now()
  returning download_count into new_count;
  return new_count;
end; $$;
grant execute on function public.register_download(text) to anon, authenticated;

create or replace function public.get_download_count(p_patch_key text)
returns bigint language sql stable security definer set search_path=public as $$
  select coalesce((select download_count from public.download_stats where patch_key=p_patch_key),0);
$$;
grant execute on function public.get_download_count(text) to anon, authenticated;

create or replace function public.is_admin(uid uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles where id=uid and role='admin');
$$;

-- Profiles
 drop policy if exists "profiles public read" on public.profiles;
create policy "profiles public read" on public.profiles for select using (true);
 drop policy if exists "profiles own update" on public.profiles;
create policy "profiles own update" on public.profiles for update using (auth.uid()=id) with check (auth.uid()=id);
revoke update on public.profiles from authenticated;
grant update(display_name, avatar_url) on public.profiles to authenticated;

-- Comments
 drop policy if exists "comments public read" on public.comments;
create policy "comments public read" on public.comments for select using (deleted_at is null or public.is_admin());
 drop policy if exists "comments user insert" on public.comments;
create policy "comments user insert" on public.comments for insert to authenticated with check (
  auth.uid()=user_id and exists(select 1 from public.profiles p where p.id=auth.uid() and not p.banned and (p.muted_until is null or p.muted_until <= now()))
);

-- Poll
 drop policy if exists "poll read" on public.poll_votes;
create policy "poll read" on public.poll_votes for select using (true);
 drop policy if exists "poll own insert" on public.poll_votes;
create policy "poll own insert" on public.poll_votes for insert to authenticated with check (auth.uid()=user_id and exists(select 1 from public.profiles p where p.id=auth.uid() and not p.banned));
 drop policy if exists "poll own update" on public.poll_votes;
create policy "poll own update" on public.poll_votes for update to authenticated using (auth.uid()=user_id) with check (auth.uid()=user_id and exists(select 1 from public.profiles p where p.id=auth.uid() and not p.banned));

-- Presence sadece güvenli RPC üzerinden
revoke all on public.presence from anon, authenticated;

create or replace function public.heartbeat_presence(p_session_id uuid)
returns integer language plpgsql security definer set search_path=public as $$
declare c integer;
begin
  insert into public.presence(session_id,user_id,last_seen) values(p_session_id,auth.uid(),now())
  on conflict(session_id) do update set user_id=auth.uid(), last_seen=now();
  select count(*) into c from public.presence where last_seen > now() - interval '2 minutes';
  return c;
end; $$;
grant execute on function public.heartbeat_presence(uuid) to anon, authenticated;

-- Admin RPC'leri
create or replace function public.admin_list_users(p_search text default '')
returns table(id uuid,email text,display_name text,role text,banned boolean,muted_until timestamptz,created_at timestamptz)
language plpgsql security definer set search_path=public,auth as $$
begin
  if not public.is_admin() then raise exception 'not authorized'; end if;
  return query select u.id,u.email,p.display_name,p.role,p.banned,p.muted_until,p.created_at
  from auth.users u join public.profiles p on p.id=u.id
  where coalesce(p_search,'')='' or p.display_name ilike '%'||p_search||'%' or u.email ilike '%'||p_search||'%'
  order by p.created_at desc limit 500;
end; $$;
grant execute on function public.admin_list_users(text) to authenticated;

create or replace function public.admin_list_comments(p_limit integer default 100)
returns table(id bigint,page text,body text,created_at timestamptz,user_id uuid,display_name text)
language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'not authorized'; end if;
  return query select c.id,c.page,c.body,c.created_at,c.user_id,p.display_name from public.comments c join public.profiles p on p.id=c.user_id where c.deleted_at is null order by c.created_at desc limit least(greatest(p_limit,1),500);
end; $$;
grant execute on function public.admin_list_comments(integer) to authenticated;

create or replace function public.admin_set_user_status(p_user_id uuid,p_banned boolean default null,p_muted_until timestamptz default null)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'not authorized'; end if;
  if p_user_id=auth.uid() then raise exception 'cannot moderate self'; end if;
  update public.profiles set banned=coalesce(p_banned,banned), muted_until=case when p_muted_until is null then muted_until else p_muted_until end where id=p_user_id and role<>'admin';
end; $$;
grant execute on function public.admin_set_user_status(uuid,boolean,timestamptz) to authenticated;

create or replace function public.admin_delete_comment(p_comment_id bigint)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'not authorized'; end if;
  update public.comments set deleted_at=now() where id=p_comment_id;
end; $$;
grant execute on function public.admin_delete_comment(bigint) to authenticated;

-- ÖNEMLİ: İlk admin hesabını oluşturduktan sonra aşağıdaki satırı kendi e-postanızla çalıştırın:
-- update public.profiles set role='admin' where id=(select id from auth.users where email='SENIN_EPOSTAN@example.com');
